### ISSUE TITLE
Customize My_settings.h

### ISSUE THREAD

**Issue by felipemanga** [felipemanga/PyInSky#3]
It would be useful to customize the defines in `My_settings.h`.

On the client side, this could be done using Python comments:
`#define PROJ_DEVELOPER_MODE 1`
Conveniently, C preprocessor definitions can simply be pasted into Python files.

Two problems to be solved for this to work:

- Changing a define means the entire PokittoLib to need to be recompiled. This is slow, so right now it's only done once and all further compiles (for all projects and users) link to the same compiled PokittoLib. This will have to be changed. The server will need to store a project folder and each project will have its own compiled PokittoLib so that changing a setting only impacts your own build time and not everyone's.

- Right now the server accepts a bunch of compiled python files. Comments not included. Client-side will need to do the processing to get the defines and send them separately.

Another issue is that the Sprite mode will break if the user changes the screen mode. It can be "fixed" but pixels will be stretched and ugly.

**Comment by HomineLudens** [comment]
Do we really need to have different PokittoLib version? From what I get uPython leave very little free resources and High Res mode would be very hard.
To skip the boot sequence we could have something (special address) that could be detected by the Simulator. 
The FPS can be easily printed on console.
KISS

**Comment by felipemanga** [comment]
It's not an urgent need... but text games would benefit from higher resolution and Mars Attack proves that it is viable. Still, it causes problems with sprite mode, so for now, this is just an idea that needs to simmer for a bit before it can be implemented. Maybe after the compo's over.

**Comment by haviital** [comment]
Btw. As I need to add support for analog pin input to MP (due the "Joyhat" support), I will also add time function. With that everyone can print the FPS figure themselves. No need for the define for that either.

**Comment by felipemanga** [comment]
Implemented "flags" tab for this.
