### ISSUE TITLE
Odd width images should be padded to multiples of two.

### ISSUE THREAD

**Issue by HomineLudens** [felipemanga/PyInSky#4]
With this image 9x10

![2](https://user-images.githubusercontent.com/1007007/54073708-c2a4a180-428a-11e9-9b55-d0dbc96db5d9.png)

outuput is this:

2Pixels = b'\
\x00\x08\x88\x80\x2Pixels = b'\
\x00\x08\x88\x80\x0\
\x00\x84\x44\x48\x0\
\x08\x44\x44\x48\x0\
\x08\x44\x04\x08\x0\
\x08\x44\x44\x48\x0\
\x08\x49\x99\x98\x0\
\x89\x99\x99\x99\x8\
\xc4\x09\x99\x04\xc\
\x00\x99\x99\x90\x0\
\x00\x89\x99\x80\x0\
'

**Comment by felipemanga** [comment]
Fixed, will deploy this soon.

**Comment by HomineLudens** [comment]
Seems ok for me
