### ISSUE TITLE
When importing from zip, editor should be refreshed

### ISSUE THREAD

**Issue by HomineLudens** [felipemanga/PyInSky#5]
Importing a zipped project with main.py open doesn't refresh already open text editor.
Also edited file is not removed even if not present in imported project.

**Comment by felipemanga** [comment]
The former seems to be a bug. It happens on my desktop, but not on my laptop. Will need to investigate.
The latter is because importing is just that, replacing/adding to the project, so it doesn't remove anything.

**Comment by felipemanga** [comment]
I think this was fixed so I'm closing it. Feel free to open a new issue if you manage to see the bug again.
